// layout
import TheHeader from "./TheHeader";
import TheFooter from "./TheFooter";
import Head from "next/head";
import TheSidebar from "./TheSidebar/TheSidebar";

export default function TheLayout({ children }) {
  return (
    <div>
      <Head>
        <title>Dashboard website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


{/* layout */}
      <TheSidebar />
      <div>
        <TheHeader />
        <main>{children}</main>
        <TheFooter />
      </div>
    </div>
  );
}
