import TheHeader from "./TheHeader";
import TheFooter from "./TheFooter";
import Head from "next/head";
import TheSidebar from "./TheSidebar/TheSidebar";

export default function TheLayout({ children }) {
  return (
    <div>
      <Head>
        <title>Dashboard website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
         {/* open graph */}
        <meta property="og:title" content="dashboard website" />
        <meta property="og:site_name" content="dashboard website" />
        <meta property="og:url" content="http://localhost:8080/" />
        <meta property="og:description" content="Open graph technology was first introduced by facebook in 2010. it allows any web page to have the same functionality as other objects facebook. a user integrate their website with all social media sites; linkedin, twitter and google+ recognized advantage of meta tags them. has launched its own cards if robots can’t find on they use open instead." />
        <meta property="og:type" content="website" />
        <meta property="og:image" content="https://media.nature.com/lw1024/magazine-assets/d43978-020-00011-4/d43978-020-00011-4_18482702.jpg" />
        {/* twitter card */}
        <meta name="twitter:card" content="summary_large_image"/>
       <meta name="twitter:site" content="@dashboad website"/>
        <meta name="twitter:title" content="dashboard website"/>
        <meta name="twitter:description" content="graph technology was first introduced by facebook in 2010. it allows any web page to have the same functionality as other objects facebook. a user integrate their website with all social media sites; "/>
<meta name="twitter:image" content="https://media.nature.com/lw1024/magazine-assets/d43978-020-00011-4/d43978-020-00011-4_18482702.jpg"/>  
      </Head>

      {/*application layout */}
      <div id="mySideBar">
        <TheSidebar />
        <>
          <TheHeader />
          <main>{children}</main>
          <TheFooter />
        </>
      </div>
    </div>
  );
};
